# Generated by Django 5.2.8 on 2025-11-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('notification_period', models.IntegerField(choices=[(1, '1 Hour'), (3, '3 Hours'), (6, '6 Hours'), (12, '12 Hours')])),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook')], max_length=10)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
